// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcnlblfizmrxvoklwjny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jbmxibGZpem1yeHZva2x3am55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzAxNTYsImV4cCI6MjA3MDE0NjE1Nn0.1FoHMmHx3a_cUro2-7h2SjPDQ5N5u4xCD6n0DfudFJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});